defaults:
  - _self_
  - algo: pupgsc
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled


# task settings
env: Alien-v5
resize: ${algo.resize}
num_envs: ${algo.num_envs}
run: 6
eval_times: 100
seed: ???

# RGB or RAM
ram: False
gray: True
fs: 4

# saving training situations settings
base_path: ./results/ALE/${env}/${algo.algo_name}
save_path: ???
tb: True
log: True

# saving network parameters settings
model: False
model_path: ???
model_list: [ 100000, 500000, 1000000, 2000000, 5000000 ]

# cuda settings
cuda: True
cuda_deterministic: True


# DO NOT CHANGE
hydra:
  output_subdir: null
  run:
    dir: .