defaults:
  - _self_
algo_name: pupgsc


resize: 84
num_envs: 1
eval_times: ${eval_times}

max_steps: 100000
buffer_size: 100000
learning_rate: 1e-4
eps: 0.000015
learning_starts: 1600
batch_size: 32
gamma: 0.99
target_network_freq: 1000
train_freq: 4

# rainbow network structure
adapter_out_features: 512
q_hidden_features: 512


# rainbow
n_atoms: 51
v_max: 10
v_min: -10
data_efficient: False
noisy_std: 0.1
log_softmax: False
n_steps: 20
alpha: 0.6
step_size: 3
lr_decay_factor: 0.1
beta_s: 0.45
epsilon: 0.1

#pupg
padding: 4
lambd: 0.0051
cl_coef: 0.01
bt_coef: 1e-4
p: 2
tau: 0.99